server {
    listen 8080;
    server_name localhost;
    host 0.0.0.0;
    root docs/fusion_web/;        # Aquí van tus archivos HTML
    index index.html;
    error_page 404 error_pages/404.html;

    # Raíz /
    location / {
        allow_methods GET DELETE POST;
        autoindex off;
    }

    # /tours
    location /tours1 {
        allow_methods GET POST;
        index tours1.html;
        autoindex off;
    }

    # /red → redirige a /tours
    location /red {
        return /tours1;
    }
}