server {
    listen 8080;
    server_name localhost;
    host 0.0.0.0;
    root docs/fusion_web/;
    index index.html;

    # REQUISITO: / solo debe responder a GET
    location / {
        allow_methods GET;
        autoindex off;
		cgi_path ./cgi_tester; # Ruta al ejecutable que te dan
        cgi_ext .bla;

    }

    # REQUISITO: /post_body responde a POST con maxBody 100
    location /post_body {
        allow_methods POST;
        #client_max_body_size 100;
    }

    # REQUISITO: /directory/ con raíz YoupiBanane e index youpi.bad_extension
    # Nota: Si YoupiBanane es una carpeta dentro de tu repo, pon la ruta completa
    location /directory/ {
        allow_methods GET POST; # El tester a veces pide POST aquí también
       	alias YoupiBanane/;     # O la ruta donde esté la carpeta
        index youpi.bad_extension;
    }

    # REQUISITO CRÍTICO: Cualquier .bla debe ejecutar el cgi_test
    # En el webserv de 42, esto suele manejarse por extensión:
}
#------------------------------------------
#           📌 SUMMARY 📌
# Configuration files allow us to:
#
#   ◉ Define servers and ports
#   ◉ Control routing behavior
#   ◉ Restrict HTTP methods
#   ◉ Manage uploads safely
#   ◉ Execute CGI scripts
#   ◉ Customize error handling
#
# For more info go to our wiki
#------------------------------------------


server {
    listen 8081;
	server_name localhost;
    host 0.0.0.0;
    root docs/fusion_web/;
    # client_max_body_size 3000000;
	index index.html;
    error_page 404 /error_pages/404.html;

    location / {
        allow_methods  DELETE POST GET;
        autoindex off;
    }
    
    location /tours {
        autoindex on;
        index tours1.html;
        allow_methods GET POST;
    }

	location /red {
		return /tours;
	}

    location /cgi-bin {
        root docs/cgi-bin;
        allow_methods GET POST DELETE;
        autoindex off;
        index time.py;
        cgi_path /usr/bin/python3 /bin/bash;
        cgi_ext .py .sh;
    }
}
