
#------------------------------------------
#           📌 TESTER config 📌
# Setup the configuration file as follow:
# - / must answer to GET request ONLY
# - Any file with .bla as extension must answer to POST request by calling the cgi_test executable
# - /post_body must answer anything to POST request with a maxBody of 100
# - /directory/ must answer to GET request and the root of it would be the repository YoupiBanane and if no file are requested, it should search for youpi.bad_extension files
#------------------------------------------

server {
    listen 8080;
    server_name localhost;
    host 0.0.0.0;
    root docs/fusion_web/;
    index index.html;

    # REQUISITO: / solo debe responder a GET
    location / {
        allow_methods GET;
        autoindex off;

    }

    # REQUISITO: /post_body responde a POST con maxBody 100
    location /post_body {
        allow_methods POST;
        client_max_body_size 100;
    }

    # REQUISITO: /directory/ con alias a YoupiBanane e index youpi.bad_extension
    # Nota: Si YoupiBanane es una carpeta dentro de tu repo, pon la ruta completa
    # Si la extensión está en cgi_ext, permite POST además de GET, incluso si allow_methods solo dice GET.
    location /directory/ {
        allow_methods GET;
        alias YoupiBanane;
        index youpi.bad_extension;
        cgi_path ../cgi_tester;
        cgi_ext .bla;
    }

    # REQUISITO CRÍTICO: Cualquier .bla debe ejecutar el cgi_test
    # En el webserv de 42, esto suele manejarse por extensión:
}
#------------------------------------------
#           📌 SUMMARY 📌
# Configuration files allow us to:
#
#   ◉ Define servers and ports
#   ◉ Control routing behavior
#   ◉ Restrict HTTP methods
#   ◉ Manage uploads safely
#   ◉ Execute CGI scripts
#   ◉ Customize error handling
#
# For more info go to our wiki
#------------------------------------------


server {
    listen 8081;
	server_name localhost;
    host 0.0.0.0;
    root docs/fusion_web/;
    # client_max_body_size 3000000;
	index index.html;
    error_page 404 /error_pages/404.html;

    location / {
        allow_methods  DELETE POST GET;
        autoindex off;
    }

    location /tours {
        autoindex on;
        index tours1.html;
        allow_methods GET POST;
    }

	location /red {
		return /tours;
	}

    location /cgi-bin {
        root docs/cgi-bin;
        allow_methods GET POST DELETE;
        autoindex off;
        index time.py;
        cgi_path /usr/bin/python3 /bin/bash;
        cgi_ext .py .sh;
    }
}
