server {
    listen 8080;
    server_name localhost;
    host 0.0.0.0;

    root docs/fusion_web/;
    index index.html;

    error_page 404 /error_pages/404.html;

    #################################################
    # ROOT
    #################################################

    location / {
        allow_methods GET;
        autoindex off;
    }

    #################################################
    # POST BODY LIMIT
    #################################################

    location /post_body {
        allow_methods POST;
        client_max_body_size 100;
        upload_path ./upload;
        autoindex off;
    }

    #################################################
    # FILE UPLOAD
    #################################################

    location /upload {
        allow_methods GET POST;
        client_max_body_size 10485760;
        upload_path ./upload;
        autoindex off;
    }

    #################################################
    # DIRECTORY + INDEX + CGI
    #################################################

    location /directory/ {
        allow_methods GET;
        alias ./YoupiBanane/;

        index youpi.bla;

        cgi_path ../cgi_tester;
        cgi_ext .bla;

        autoindex off;
    }

    #################################################
    # AUTOINDEX ON
    #################################################

    location /list/ {
        allow_methods GET;
        alias ./YoupiBanane/;
        #index hola.html;
        autoindex on;
    }

    #################################################
    # DELETE TEST
    #################################################

    location /delete {
        allow_methods DELETE;
        alias ./delete_test/;
    }

    #################################################
    # REDIRECTION
    #################################################

    location /redir {
        return /directory/;
    }
}