#----------------------------------------------------------
#                   📌 CONF FILES 📌
#  ◉ manual_test.conf
#
#  - General-purpose config for manual testing and debugging
#  - Enables:
#       • Static file serving
#       • POST handling
#       • DELETE requests
#       • CGI execution via /cgi-bin
#       • Redirect testing
#       • Custom 404 error page
#----------------------------------------------------------

server {
    listen 8080;
    server_name localhost;
    host 0.0.0.0;
    root docs/fusion_web/;
    index index.html;
    error_page 404 /error_pages/404.html;

    location / {
        allow_methods GET POST DELETE;
        autoindex off;
    }

    location /post_body {
        allow_methods POST;
        client_max_body_size 100;
        upload_path ./uploads;
        autoindex off;
    }

    location /tours {
        allow_methods GET POST;
        autoindex off;
        index tours1.html;
    }

    location /red {
        return /tours;
    }

    location /directory/ {
        allow_methods GET;
        alias ./YoupiBanane/;
        index youpi.bad_extension;
        autoindex off;
    }

    location /cgi-bin {
        root docs/cgi-bin;
        allow_methods GET POST DELETE;
        autoindex off;
        index time.py;
        cgi_path /usr/bin/python3 /bin/bash;
        cgi_ext .py .sh;
    }
}