#---------------------------------------------------------
#                   📌 CONF FILES 📌
#  ◉ nocgi.conf
#
#   - Simplified configuration without CGI support
#   - Focuses on:
#       • Static routing
#       • Redirections
#       • Method handling
#   - Useful to isolate and test core HTTP behavior
#----------------------------------------------------------

server {
    listen 8080;
    server_name localhost;
    host 0.0.0.0;
    root docs/fusion_web/;
    index index.html;
    error_page 404 /error_pages/404.html;

    # Root /
    location / {
        allow_methods GET DELETE POST;
        autoindex off;
    }

    # /tours
    location /tours1 {
        allow_methods GET POST;
        index tours1.html;
        autoindex off;
    }

    # /red → redirige a /tours
    location /red {
        return /tours1;
    }
}
